# Generated by Django 5.0.9 on 2026-09-14 17:46

import catalog.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Congregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('primary_language', models.CharField(max_length=50)),
                ('secondary_languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Additional languages served by this congregation.', size=None)),
                ('bilingual_display_default', models.CharField(choices=[('none', 'None'), ('stacked', 'Stacked'), ('side_by_side', 'Side by side')], default='none', max_length=20)),
                ('default_sheet_format', models.CharField(choices=[('chord_chart', 'Chord chart'), ('lead_sheet', 'Lead sheet'), ('piano_score', 'Piano score'), ('hymnal', 'Hymnal'), ('vocal_only', 'Vocal only')], default='chord_chart', max_length=20)),
                ('song_restrictions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Notes on songs this congregation avoids (e.g. theology, style).', size=None)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('theme', 'Theme'), ('scripture_ref', 'Scripture reference'), ('season', 'Season'), ('language', 'Language'), ('mood', 'Mood')], max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('alternate_titles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, default=list, size=None)),
                ('ccli_number', models.CharField(help_text="CCLI song number, or 'Public Domain' if not licensed.", max_length=50)),
                ('copyright_holder', models.CharField(max_length=300)),
                ('licensing_notes', models.TextField(blank=True)),
                ('default_key', models.CharField(blank=True, max_length=10)),
                ('tempo', models.PositiveIntegerField(blank=True, help_text='Beats per minute.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs_created', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='songs', to='catalog.tag')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('rotation_schedule', models.TextField(blank=True, help_text='Optional free-text rotation notes.')),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='catalog.congregation')),
            ],
            options={
                'ordering': ['congregation__name', 'name'],
                'unique_together': {('congregation', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SheetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('chord_chart', 'Chord chart'), ('lead_sheet', 'Lead sheet'), ('piano_score', 'Piano score'), ('hymnal', 'Hymnal'), ('vocal_only', 'Vocal only')], max_length=20)),
                ('key', models.CharField(blank=True, max_length=10)),
                ('file', models.FileField(upload_to=catalog.models.sheet_upload_path)),
                ('source', models.CharField(choices=[('purchased', 'Purchased'), ('transcribed', 'Transcribed'), ('arranged', 'Arranged')], default='purchased', max_length=20)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheets_uploaded', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='catalog.song')),
                ('preferred_by_teams', models.ManyToManyField(blank=True, related_name='preferred_sheets', to='catalog.team')),
            ],
            options={
                'ordering': ['song__title', 'type', 'key'],
            },
        ),
        migrations.CreateModel(
            name='LyricAlignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_language', models.CharField(max_length=50)),
                ('secondary_language', models.CharField(max_length=50)),
                ('line_pairing', models.JSONField(blank=True, default=list, help_text='Confirmed segment/line correspondence across languages.')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignments', to='catalog.song')),
            ],
            options={
                'ordering': ['song__title'],
                'unique_together': {('song', 'primary_language', 'secondary_language')},
            },
        ),
        migrations.CreateModel(
            name='SongLyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(max_length=50)),
                ('segments', models.JSONField(blank=True, default=list, help_text='List of segments, e.g. [{"segment_type": "verse1", "lines": ["...", "..."]}]')),
                ('translation_source', models.CharField(choices=[('official', 'Official'), ('team_translated', 'Team translated'), ('ai_assisted', 'AI assisted')], default='official', max_length=20)),
                ('status', models.CharField(choices=[('original', 'Original'), ('translated_unverified', 'Translated (unverified)'), ('translated_verified', 'Translated (verified)'), ('needs_translation', 'Needs translation'), ('needs_alignment', 'Needs alignment')], default='original', max_length=25)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='catalog.song')),
            ],
            options={
                'verbose_name_plural': 'Song lyrics',
                'ordering': ['song__title', 'language'],
                'unique_together': {('song', 'language')},
            },
        ),
    ]
