# Generated by Django 5.0.9 on 2026-09-14 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyricalignment',
            name='owner_team',
            field=models.ForeignKey(blank=True, help_text='Team that owns this content. Null = admin-owned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_alignments', to='catalog.team'),
        ),
        migrations.AddField(
            model_name='sheetfile',
            name='owner_team',
            field=models.ForeignKey(blank=True, help_text='Team that owns this content. Null = admin-owned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_sheets', to='catalog.team'),
        ),
        migrations.AddField(
            model_name='song',
            name='owner_team',
            field=models.ForeignKey(blank=True, help_text='Team that owns this content. Null = admin-owned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_songs', to='catalog.team'),
        ),
        migrations.AddField(
            model_name='songlyrics',
            name='owner_team',
            field=models.ForeignKey(blank=True, help_text='Team that owns this content. Null = admin-owned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_lyrics', to='catalog.team'),
        ),
    ]
