# Generated by Django 5.0.9 on 2026-09-14 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_lyricalignment_owner_team_sheetfile_owner_team_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='reference_url',
            field=models.URLField(blank=True, help_text='Reference recording (YouTube/Spotify/any link) for listening.'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('title', models.CharField(blank=True, help_text='Occasion or theme (optional).', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('congregation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='catalog.congregation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_created', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catalog.team')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('key_override', models.CharField(blank=True, max_length=10)),
                ('format_override', models.CharField(blank=True, choices=[('chord_chart', 'Chord chart'), ('lead_sheet', 'Lead sheet'), ('piano_score', 'Piano score'), ('hymnal', 'Hymnal'), ('vocal_only', 'Vocal only')], max_length=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.service')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_appearances', to='catalog.song')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
